/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RecognizeRouteImport } from './routes/recognize'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTranslateTextRouteImport } from './routes/api/translate/text'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RecognizeRoute = RecognizeRouteImport.update({
  id: '/recognize',
  path: '/recognize',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateTextRoute = ApiTranslateTextRouteImport.update({
  id: '/api/translate/text',
  path: '/api/translate/text',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recognize': typeof RecognizeRoute
  '/translate': typeof TranslateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/translate/text': typeof ApiTranslateTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recognize': typeof RecognizeRoute
  '/translate': typeof TranslateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/translate/text': typeof ApiTranslateTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/recognize': typeof RecognizeRoute
  '/translate': typeof TranslateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/translate/text': typeof ApiTranslateTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/recognize'
    | '/translate'
    | '/api/health'
    | '/api/translate/text'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/recognize'
    | '/translate'
    | '/api/health'
    | '/api/translate/text'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/recognize'
    | '/translate'
    | '/api/health'
    | '/api/translate/text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RecognizeRoute: typeof RecognizeRoute
  TranslateRoute: typeof TranslateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTranslateTextRoute: typeof ApiTranslateTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recognize': {
      id: '/recognize'
      path: '/recognize'
      fullPath: '/recognize'
      preLoaderRoute: typeof RecognizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate/text': {
      id: '/api/translate/text'
      path: '/api/translate/text'
      fullPath: '/api/translate/text'
      preLoaderRoute: typeof ApiTranslateTextRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RecognizeRoute: RecognizeRoute,
  TranslateRoute: TranslateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTranslateTextRoute: ApiTranslateTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
